### ISSUE TITLE
TypeError: Path must be a string. Received [ 'test/svg/test.svg' ]

### ISSUE THREAD

**Issue by matatk** [runspired/grunt-phantom-rasterize#5]
This looks like it will be a really useful module to me; thanks.  Unfortunately, I am getting the above error when trying to run any task involving it. This is what I did to get the error:
1. Clone this repo.
2. `npm install`
3. `grunt`

I'm not sure which library is the root cause of this; it does seem that quite a few people have experienced similar errors (with various libraries) in the transition to node 6 from node 5, but I haven't been able to find out any more.  Was wondering if you are able to reproduce this?

**Comment by menocomp** [comment]
I have the same error, and the fix is to add this line:
`item.file.src = item.file.src[0];`
as the first line in this function
`async.eachLimit(output, options.limit, function (item, next)`

**Comment by runspired** [comment]
A PR with the fix is welcome.

**Comment by runspired** [comment]
I'd also be interested in adding a maintainer, as I do not actively use this repo anymore.

**Comment by matatk** [comment]
@menocomp thanks; your fix works for me.

@runspired I've just made a PR (#6) that is @menocomp's fix for this. Sorry I don't have the cycles to be a maintainer, but I have a feeling this repo will do just what I need (and more cross-platform than the hack I knocked up) so I'm looking forward to trying it out :-).

**Comment by matatk** [comment]
I've just been able to try this in my own project and found, to my surprise, that it still gives me the TypeError.  I can't figure out why currently, but by removing the line that my patch added, and then appending the `[0]` to the first two occurrences of `item.files.src` in the same function, this does seem to fix it.  It seems like a bit of a hack so I'm going to have to look into this further I think. I suspect the API for dealing with input files within Grunt plugins changed, and the only way to fix this properly is to fix it properly as-it-were :-). Will write back when I have more info...

**Comment by matatk** [comment]
I found out a bit more and created #7 to address the problem (at least partly, but, I think, more robustly than before).

**Comment by matatk** [comment]
I've come to the conclusion that the root cause of this bug is that there can be more than one `src` file per destination file. (I expect this is obvious, but I think I now understand why Grunt sees the world this way.)

Currently this is how grunt-phantom-rasterize works:

```
for each source file
    for each target size
        rasterise source file to target size
```

However, when one looks at the task's `this.files` object, supplied by Grunt, one sees something like this:

```
[ { src: [ 'test/svg/test.svg' ],
    orig: { expand: true, cwd: 'test/svg', src: [Object], ext: '.png' },
    dest: 'test.png' } ]
```

It dawned on me from looking at the code again, and [Grunt docs](http://gruntjs.com/configuring-tasks#compact-format), that what Grunt thinks we should be doing is having an extra loop in here:

```
for each file in this.files
    for each src file in file.src
        for each target size
            rasterise src to target size
```

Of course this makes no sense for grunt-phantom-rasterize, as the result of doing this would just be that the `dest` gets overwritten with the last item from `src`.  But, if you think about other Grunt plugins, which might cat (or otherwise join) multiple files together (e.g. when compiling several JS units into a larger file), being able to specify more than one source file per destination makes sense, so Grunt allows it, hence `file.src` is an array - because that would be useful for most types of Grunt plugin.

Therefore the solution to the problem is probably to detect if the array is longer than one item, and throw an error, so as to avoid a `dest` getting overwritten.

So I have now come full circle (with one extra bit added--the warning/error message), but I think I understand this a lot better now.  I guess this is one of those rare cases when it _does_ make sense to mandate that `src` be of length one.
